POST http://127.0.0.1:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "Diamond",
    "email": "testemail@gmail.com",
    "password": "123123yoyo"
}

###

GET http://127.0.0.1:8000/api/users/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NzI5ODExLCJpYXQiOjE3NTU3Mjk1MTEsImp0aSI6IjdjNzIxYTI3MjgxNjRiMDJiODg3NTA3NjBlODNmMzExIiwidXNlcl9pZCI6IjEifQ.kcHUdwH6G0Yfi3_VEihcNGrp2UM0qZ9-BxOpl_Lj_x4
###

POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTgxNTYxMSwiaWF0IjoxNzU1NzI5MjExLCJqdGkiOiJlOTdlNTQ4MzM5YzI0YTIzODk4OWFlNWQ3MTYzNWU1ZCIsInVzZXJfaWQiOiIxIn0.es6lObgKLP2uc9F_jvmGz8SMnv5Yy2ojJllCXYiriEE"
}

###
POST http://127.0.0.1:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "Diamond",
    "password": "123123yoyo"
}

###

POST  http://127.0.0.1:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NzI5ODExLCJpYXQiOjE3NTU3Mjk1MTEsImp0aSI6IjdjNzIxYTI3MjgxNjRiMDJiODg3NTA3NjBlODNmMzExIiwidXNlcl9pZCI6IjEifQ.kcHUdwH6G0Yfi3_VEihcNGrp2UM0qZ9-BxOpl_Lj_x4
###

GET http://127.0.0.1:8000/api/products/1 HTTP/1.1
Content-Type: application/json

{
    "pk": 1
}

###

POST http://127.0.0.1:8000/api/orders/ HTTP/1,1
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/cart/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1Nzk3NDMxLCJpYXQiOjE3NTU3OTcxMzEsImp0aSI6ImQ4Yjk0NTJkODlkNjQxZTdiODI0NzQyZDRmZWQzZjIxIiwidXNlcl9pZCI6IjIifQ.jB_HgI3tun2uFhAvM5exSA4WIGuJPRHVkGLipuMB1Q0

###

POST http://127.0.0.1:8000/api/cart/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1Nzk5ODg0LCJpYXQiOjE3NTU3OTk1ODQsImp0aSI6IjhlNTdlY2QxZGQxMDQwNzk4MjYyMzYxYTQ1MmQ2OTBlIiwidXNlcl9pZCI6IjIifQ.BHDH3yH2Ljf-U349XSPJlmkf6wg0TlylZnqpYqd6pbU

{
    "product_id": 1
}