POST http://127.0.0.1:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "Diamond",
    "email": "testemail@gmail.com",
    "password": "123123yoyo"
}

###

GET http://127.0.0.1:8000/api/users/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NzI5ODExLCJpYXQiOjE3NTU3Mjk1MTEsImp0aSI6IjdjNzIxYTI3MjgxNjRiMDJiODg3NTA3NjBlODNmMzExIiwidXNlcl9pZCI6IjEifQ.kcHUdwH6G0Yfi3_VEihcNGrp2UM0qZ9-BxOpl_Lj_x4
###

POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTgxNTYxMSwiaWF0IjoxNzU1NzI5MjExLCJqdGkiOiJlOTdlNTQ4MzM5YzI0YTIzODk4OWFlNWQ3MTYzNWU1ZCIsInVzZXJfaWQiOiIxIn0.es6lObgKLP2uc9F_jvmGz8SMnv5Yy2ojJllCXYiriEE"
}

###
POST http://127.0.0.1:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "Diamond",
    "password": "123123yoyo"
}

###

POST  http://127.0.0.1:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1ODIyNDE0LCJpYXQiOjE3NTU4MjIxMTQsImp0aSI6ImZkMDNkYjRjNDA5OTQ1OTdhMTI3ZDA2NWYwYzZhYWJiIiwidXNlcl9pZCI6IjIifQ.BPXRzgiwKx14debztc-siUDKPz7XudznwurZPJZnbcY
###

GET http://127.0.0.1:8000/api/products/1 HTTP/1.1
Content-Type: application/json

{
    "pk": 1
}

###

POST http://127.0.0.1:8000/api/order/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MDc2Njg1LCJpYXQiOjE3NTYwNzYzODUsImp0aSI6IjlmZTY4MWNhMTVlODRiYjY5NDNkZTljMjNiMDNkZDc0IiwidXNlcl9pZCI6IjIifQ.ms10QHv3ExEPi-Y8uz-bu9Zh0Mo5IAG-bTXpFhlVyZ8

{
    "product_id": 2
}
###

GET http://127.0.0.1:8000/api/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTg0Mzg0LCJpYXQiOjE3NTU5ODQwODQsImp0aSI6IjYzNTMzOTZiOGM0ODQzZmI5MGYyYTVkNDRiMzg3MThhIiwidXNlcl9pZCI6IjIifQ.qFOCacDyI4Q99Qe5kuUOZqWFxhF-ZJGgMVMBJ9s5p5Q

###
POST http://127.0.0.1:8000/api/cart/add/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MDczOTIwLCJpYXQiOjE3NTYwNzM2MjAsImp0aSI6IjRjOGY2ZjE2MTE5MTRiYzVhMDU3ZjhkMDUyZDA1NWJlIiwidXNlcl9pZCI6IjIifQ.nellvjsLhgvmqdoPbY60AkcohCsJ2oX_W4TexY-vBEI

{
    "product_id": 2
}
###

PUT http://127.0.0.1:8000/api/cart/update/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTg0Mzg0LCJpYXQiOjE3NTU5ODQwODQsImp0aSI6IjYzNTMzOTZiOGM0ODQzZmI5MGYyYTVkNDRiMzg3MThhIiwidXNlcl9pZCI6IjIifQ.qFOCacDyI4Q99Qe5kuUOZqWFxhF-ZJGgMVMBJ9s5p5Q

{
    "quantity": 1
}

###

PATCH http://127.0.0.1:8000/api/cart/update/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTg0Mzg0LCJpYXQiOjE3NTU5ODQwODQsImp0aSI6IjYzNTMzOTZiOGM0ODQzZmI5MGYyYTVkNDRiMzg3MThhIiwidXNlcl9pZCI6IjIifQ.qFOCacDyI4Q99Qe5kuUOZqWFxhF-ZJGgMVMBJ9s5p5Q

{
    "product_id": 1,
    "quantity": 1
}

###

POST http://127.0.0.1:8000/api/make-payment/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MDgyNTI5LCJpYXQiOjE3NTYwODIyMjksImp0aSI6IjYyNjQzNDhjZWFiNzQ1ZDhiM2M2NzUwMDI2ZWNmZGRkIiwidXNlcl9pZCI6IjIifQ.sKs9boh1KZmiO3gp1ccSX6wQiW9jWCcVTfntZj5UQV4